### ISSUE TITLE
AttributeError: module 'control' has no attribute 'TransferFunction'

### ISSUE THREAD

**Issue by jelleheijne-nps** [terrencetec/kontrol#44]
I get this error when importing kontrol.curvefit:
AttributeError: module 'control' has no attribute 'TransferFunction'

**Comment by terrencetec** [comment]
I cannot reproduce the problem.
I tried creating a new Conda environment and installing numpy, scipy, matplotlib, and control from the conda-forge channel.
```
conda create -n kontrol_test
conda activate kontrol_test
conda install -c conda-forge numpy scipy matplotlib control
```
Then, I install kontrol from the repository.
```
git clone <This repository>
cd kontrol
pip install .
```
Then the following import works without any error.
```
$ python
>>> import kontrol.curvefit
>>>
```
Would you be able to provide more information, such as the version of the ``control`` package that you're using?

```
$ python
>>> import control
>>> control.__version__
'0.9.3.post2'
>>>
```

**Comment by jelleheijne-nps** [comment]
The same version. It works in another directory. Could the issue be that I work in a directory that is also called control?

**Comment by terrencetec** [comment]
The might be the problem.

**Comment by jelleheijne-nps** [comment]
I tried moving it up a directory, so it is not inside a directory called control anymore. I reinstalled all the packages and the error still occurs.

This is the full error message:

Traceback (most recent call last):
File "", line 1007, in _find_and_load
File "", line 972, in find_and_load_unlocked
File "", line 228, in call_with_frames_removed
File "C:\Users\j.heijne\PycharmProjects\NPS_data_processing\venv\lib\site-packages\kontrol_init.py", line 7, in
from .complementary_filter.complementary_filter import ComplementaryFilter
File "C:\Users\j.heijne\PycharmProjects\NPS_data_processing\venv\lib\site-packages\kontrol\complementary_filter\complementary_filter.py", line 10, in
import kontrol.transfer_function
File "C:\Users\j.heijne\PycharmProjects\NPS_data_processing\venv\lib\site-packages\kontrol\transfer_function_init.py", line 1, in
from .transfer_function import *
File "C:\Users\j.heijne\PycharmProjects\NPS_data_processing\venv\lib\site-packages\kontrol\transfer_function\transfer_function.py", line 14, in
class TransferFunction(control.TransferFunction):
AttributeError: module 'control' has no attribute 'TransferFunction'

This is my code:

```
import numpy as np
import pandas as pd
import scipy.signal as signal
import matplotlib.pyplot as plt
import math

# Load data from CSV files
u = np.array(pd.read_csv('control/u_lp.csv').iloc[:, 0])
d = np.array(pd.read_csv('control/d_lp.csv').iloc[:, 0])
t = np.array(pd.read_csv('control/t_lp.csv').iloc[:, 0])
e = np.array(pd.read_csv('control/e_lp.csv').iloc[:, 0])

# Define sampling frequency and frequency resolution
Fs = 100
freqres = 0.05
nfft = int(Fs/freqres)

# Estimate frequency response of the sensitivity
frequencies, cross_power = signal.csd(u, d, fs=Fs, nperseg=nfft)
_, input_power = signal.welch(d, fs=Fs, nperseg=nfft)
S = cross_power / input_power
print(S)

# Estimate frequency response of the process sensitivity
frequencies, cross_power = signal.csd(e, d, fs=Fs, nperseg=nfft)
_, input_power = signal.welch(d, fs=Fs, nperseg=nfft)
PS = cross_power / input_power
print(PS)
H = -np.conj(PS) / np.conj(S)

# Plot magnitude and phase response and coherence plots
fig, (ax1, ax2) = plt.subplots(2, 1)
fig.suptitle('Sensitivity')
ax1.semilogx(frequencies, 20*np.log10(np.abs(S)))
ax1.set_ylabel('Magnitude (dB)')
ax2.semilogx(frequencies, np.angle(S, deg=True))
ax2.set_ylabel('Phase (degrees)')
ax2.set_xlabel('Frequency (Hz)')
ax1.grid()
ax2.grid()

plt.figure()
coherence = plt.cohere(u, d, nfft, Fs)
plt.title('Coherence sensitivity')
plt.xlabel('Frequency (Hz)')
plt.ylabel('Coherence')
plt.grid()

fig, (ax1, ax2) = plt.subplots(2, 1)
fig.suptitle('Process sensitivity')
ax1.semilogx(frequencies, 20*np.log10(np.abs(PS)))
ax1.set_ylabel('Magnitude (dB)')
ax2.semilogx(frequencies, np.angle(PS, deg=True))
ax2.set_ylabel('Phase (degrees)')
ax2.set_xlabel('Frequency (Hz)')
ax1.grid()
ax2.grid()

plt.figure()
plt.cohere(e, d, nfft, Fs)
plt.title('Coherence process sensitivity')
plt.xlabel('Frequency (Hz)')
plt.ylabel('Coherence')
plt.grid()

fig, (ax1, ax2) = plt.subplots(2, 1)
fig.suptitle('Plant from PS/S')
ax1.semilogx(frequencies, 20*np.log10(np.abs(H)))
ax1.set_ylabel('Magnitude (dB)')
ax2.semilogx(frequencies, np.angle(H, deg=True))
ax2.set_ylabel('Phase (degrees)')
ax2.set_xlabel('Frequency (Hz)')
ax1.grid()
ax2.grid()
# ax1.semilogx(frequencies, 20*np.log10(np.abs(H_th)))
# ax2.semilogx(frequencies, np.angle(H_th, deg=True))
legend = ['Engine model', 'Derived transfer function']

# Fitting a transfer function to the data
import kontrol.curvefit
import scipy.optimize

frequencies = frequencies[1:]
H = H[1:]
a = kontrol.curvefit.CurveFit()
a.xdata = frequencies
a.ydata = H
a.model = kontrol.curvefit.model.SimpleZPK(nzero=0, npole=1, log_args=False)
error_func = kontrol.curvefit.error_func.tf_error
weight = 1/frequencies
error_func_kwargs = {"weight": weight}
a.cost = kontrol.curvefit.Cost(error_func=error_func, error_func_kwargs=error_func_kwargs)
a.optimizer = scipy.optimize.minimize
np.random.seed(123)
x0 = np.array([0.15915494, 0.31830989])

a.optimizer_kwargs = {"x0": x0,}

res = a.fit()

plt.figure(figsize=(15, 5))
plt.subplot(121)
plt.loglog(frequencies, abs(H), label="Data")
plt.loglog(frequencies, abs(a.model(frequencies, x0)), label="Initial guess")
plt.loglog(frequencies, abs(a.yfit), ls="--", label="Fit")
plt.legend(loc=0)
plt.grid(which="both")
plt.ylabel("Amplitude")
plt.xlabel("Frequency (Hz)")
plt.subplot(122)
plt.semilogx(frequencies, np.angle(H), label="Data")
plt.semilogx(frequencies, np.angle(a.model(frequencies, x0)), label="Initial guess")
plt.semilogx(frequencies, np.angle(a.yfit), ls="--", label="Fit")
plt.legend(loc=0)
plt.grid(which="both")
plt.ylabel("Phase (rad)")
plt.xlabel("Frequency (Hz)")
plt.show()
#
print("Fitted transfer function")
print(a.optimized_args)
print(a.model.tf.minreal())
```

**Comment by terrencetec** [comment]
The first line of the error message
```
File "", line 1007, in _find_and_load
```
indicates that the problem is raised when it's calling the _find_and_load function.
Do you have any idea where's this function from and what is it actually doing?
I have trouble understanding some of the error messages as I am not familiar with Python in Windows.
I don't understand what it is trying to do and why did it converted my package inits into something like ``kontrol_init.py``.

Have you installed the kontrol package? How are you running your script? Are you typing something like
```
python <your script>
```
in your command line or are you using something like PyCharm (which I have no idea what it does).

Could you trying running the script in a command line interface?

**Comment by jelleheijne-nps** [comment]
I run it from PyCharm. This is the error message I get when I run it with Anaconda Powershell:

Traceback (most recent call last):
  File "C:\Users\j.heijne\PycharmProjects\NPS_data_processing_deployed_v1\nps-data\exercise23.py", line 80, in <module>
    import kontrol.curvefit
  File "C:\Users\j.heijne\Anaconda3\lib\site-packages\kontrol\__init__.py", line 7, in <module>
    from .complementary_filter.complementary_filter import ComplementaryFilter
  File "C:\Users\j.heijne\Anaconda3\lib\site-packages\kontrol\complementary_filter\complementary_filter.py", line 10, in <module>
    import kontrol.transfer_function
  File "C:\Users\j.heijne\Anaconda3\lib\site-packages\kontrol\transfer_function\__init__.py", line 1, in <module>
    from .transfer_function import *
  File "C:\Users\j.heijne\Anaconda3\lib\site-packages\kontrol\transfer_function\transfer_function.py", line 14, in <module>
    class TransferFunction(control.TransferFunction):
AttributeError: module 'control' has no attribute 'TransferFunction'

**Comment by terrencetec** [comment]
Can you type the following in the Powershell?

```
$ python
>>> import control
>>> control.TransferFunction
```

**Comment by jelleheijne-nps** [comment]
![image](https://user-images.githubusercontent.com/124284688/236859154-06e070b5-cae6-428c-a144-59ef239931f3.png)

**Comment by terrencetec** [comment]
Interesting.
If you type ``control.__version__`` instead does it show the version?
How about ``control.tf``?
Did you install control from conda or pip?

**Comment by terrencetec** [comment]
Apparently, it's trying to control from somewhere, likely your ``control`` directory or somewhere in the python path.
So the ``control`` you imported isn't really the ``control`` package that's imported by the ``kontrol`` package. Could you find the source and rename those ``control`` directories?

**Comment by jelleheijne-nps** [comment]
Renaming the directory solved the issue. Thanks for your help!
